FROM node:25-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code (though it will be overridden by volume in docker-compose)
COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev"]
