services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: rouch_postgres
    environment:
      POSTGRES_DB: rouch
      POSTGRES_USER: rouch_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rouch_user -d rouch"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rouch_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: rouch_redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - rouch_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: rouch_backend
    env_file: .env
    environment:
        HF_HOME: /app/.cache/hf
        TRANSFORMERS_CACHE: /app/.cache/hf/transformers
        SENTENCE_TRANSFORMERS_HOME: /app/.cache/hf/sentence_transformers
        HF_HUB_OFFLINE: 1
        TRANSFORMERS_OFFLINE: 1
#      - WATCHFILES_FORCE_POLLING=true

    # environment:
    #   - DATABASE_URL=postgresql://rouch_user:${POSTGRES_PASSWORD}@postgres:5432/rouch
    #   - QDRANT_URL=${QDRANT_URL}
    #   - QDRANT_API_KEY=${QDRANT_API_KEY}
    #   - REDIS_URL=redis://redis:6379
    #   - TELEGRAM_ENABLED=${TELEGRAM_ENABLED:-true}
    #   - AI_API_KEY=${AI_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
#      - rouch_backend_venv:/app/.venv
      - ./terms:/app/data/knowledge_base
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
#    command: >
#      sh -c "
#      uv sync --frozen &&
#      uv run alembic upgrade head &&
#      uv run uvicorn app.main:app
#      --host 0.0.0.0
#      --port 8000
#      --reload
#      --proxy-headers
#      "
    networks:
      - rouch_network

  # Frontend Mini App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      # args:
      #   - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
    container_name: rouch_frontend
    env_file: .env
#    environment:
#      - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
    ports:
      - "5180:5180"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - rouch_network
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.rouch.rule=Host(`${DOMAIN_NAME}`)
      - traefik.http.routers.rouch.entrypoints=websecure
      - traefik.http.routers.rouch.tls=true
      - traefik.http.routers.rouch.tls.certresolver=mytlschallenge
      - traefik.http.services.rouch.loadbalancer.server.port=5180

volumes:
  postgres_data:
  qdrant_data:
  redis_data:
#  rouch_backend_venv:

networks:
  rouch_network:
    driver: bridge
  web:
    external: true