"""add_message_log_and_drop_message_snapshot

Revision ID: 88d01c711cdb
Revises: d52c14c4bda0
Create Date: 2026-02-25 18:21:06.563699+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88d01c711cdb'
down_revision: Union[str, None] = 'd52c14c4bda0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('karma_plan_id', sa.String(), nullable=True),
    sa.Column('daily_plan_id', sa.String(), nullable=True),
    sa.Column('message_type', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['daily_plan_id'], ['daily_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['karma_plan_id'], ['karma_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_logs_daily_plan_id'), 'message_logs', ['daily_plan_id'], unique=False)
    op.create_index(op.f('ix_message_logs_karma_plan_id'), 'message_logs', ['karma_plan_id'], unique=False)
    op.create_index(op.f('ix_message_logs_message_type'), 'message_logs', ['message_type'], unique=False)
    op.create_index(op.f('ix_message_logs_sent_at'), 'message_logs', ['sent_at'], unique=False)
    op.create_index(op.f('ix_message_logs_user_id'), 'message_logs', ['user_id'], unique=False)
    op.drop_column('daily_plans', 'message_snapshot')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_plans', sa.Column('message_snapshot', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_message_logs_user_id'), table_name='message_logs')
    op.drop_index(op.f('ix_message_logs_sent_at'), table_name='message_logs')
    op.drop_index(op.f('ix_message_logs_message_type'), table_name='message_logs')
    op.drop_index(op.f('ix_message_logs_karma_plan_id'), table_name='message_logs')
    op.drop_index(op.f('ix_message_logs_daily_plan_id'), table_name='message_logs')
    op.drop_table('message_logs')
    # ### end Alembic commands ###
