"""remove daily suggestions

Revision ID: 4512945064a7
Revises: dba077286716
Create Date: 2026-02-26 03:38:00.988061+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4512945064a7'
down_revision: Union[str, None] = 'dba077286716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_suggestions_completed'), table_name='daily_suggestions')
    op.drop_index(op.f('ix_daily_suggestions_date'), table_name='daily_suggestions')
    op.drop_index(op.f('ix_daily_suggestions_user_id'), table_name='daily_suggestions')
    op.drop_table('daily_suggestions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_suggestions',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('why', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('seed_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['seed_id'], ['seeds.id'], name=op.f('daily_suggestions_seed_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('daily_suggestions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('daily_suggestions_pkey'))
    )
    op.create_index(op.f('ix_daily_suggestions_user_id'), 'daily_suggestions', ['user_id'], unique=False)
    op.create_index(op.f('ix_daily_suggestions_date'), 'daily_suggestions', ['date'], unique=False)
    op.create_index(op.f('ix_daily_suggestions_completed'), 'daily_suggestions', ['completed'], unique=False)
    # ### end Alembic commands ###
