"""Add problem history table

Revision ID: 57fe60c447dd
Revises: 20260129_0001
Create Date: 2026-02-04 04:26:19.824938+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57fe60c447dd'
down_revision: Union[str, None] = '20260129_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_text', sa.Text(), nullable=False),
    sa.Column('solution_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_history_created_at'), 'problem_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_problem_history_is_active'), 'problem_history', ['is_active'], unique=False)
    op.create_index(op.f('ix_problem_history_user_id'), 'problem_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_partner_actions_user_id'), 'partner_actions', ['user_id'], unique=False)
    # op.drop_constraint(op.f('partner_actions_user_id_fkey'), 'partner_actions', type_='foreignkey')
    op.create_foreign_key(None, 'partner_actions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'partner_actions', type_='foreignkey')
    # op.create_foreign_key(op.f('partner_actions_user_id_fkey'), 'partner_actions', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_partner_actions_user_id'), table_name='partner_actions')
    op.drop_index(op.f('ix_problem_history_user_id'), table_name='problem_history')
    op.drop_index(op.f('ix_problem_history_is_active'), table_name='problem_history')
    op.drop_index(op.f('ix_problem_history_created_at'), table_name='problem_history')
    op.drop_table('problem_history')
    # ### end Alembic commands ###
