"""link prompt snooze until

Revision ID: a03c6a6c46e7
Revises: e0f26ced8de8
Create Date: 2026-03-06 00:54:29.910554+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a03c6a6c46e7'
down_revision: Union[str, None] = 'e0f26ced8de8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('link_prompt_snoozed_until', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'link_prompt_dismissed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'link_prompt_dismissed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_column('users', 'link_prompt_snoozed_until')
    # ### end Alembic commands ###
