"""remove_is_active_from_problem_history

Revision ID: 3a06f1e01ddc
Revises: c56f551755dc
Create Date: 2026-02-24 02:43:02.603247+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a06f1e01ddc'
down_revision: Union[str, None] = 'c56f551755dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problem_history_is_active'), table_name='problem_history')
    op.drop_column('problem_history', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem_history', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_problem_history_is_active'), 'problem_history', ['is_active'], unique=False)
    # ### end Alembic commands ###
