"""add coffee meditation tables

Revision ID: c5b53de4dc19
Revises: ad8042a6424c
Create Date: 2026-02-27 22:34:03.936516+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5b53de4dc19'
down_revision: Union[str, None] = 'ad8042a6424c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coffee_meditation_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('karma_plan_id', sa.String(), nullable=True),
    sa.Column('daily_plan_id', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('notes_draft', sa.Text(), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['daily_plan_id'], ['daily_plans.id'], name=op.f('fk_coffee_meditation_sessions_daily_plan_id_daily_plans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['karma_plan_id'], ['karma_plans.id'], name=op.f('fk_coffee_meditation_sessions_karma_plan_id_karma_plans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_coffee_meditation_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coffee_meditation_sessions')),
    sa.UniqueConstraint('user_id', 'local_date', name='uq_coffee_session_user_local_date')
    )
    op.create_index(op.f('ix_coffee_meditation_sessions_completed_at'), 'coffee_meditation_sessions', ['completed_at'], unique=False)
    op.create_index(op.f('ix_coffee_meditation_sessions_daily_plan_id'), 'coffee_meditation_sessions', ['daily_plan_id'], unique=False)
    op.create_index(op.f('ix_coffee_meditation_sessions_karma_plan_id'), 'coffee_meditation_sessions', ['karma_plan_id'], unique=False)
    op.create_index(op.f('ix_coffee_meditation_sessions_local_date'), 'coffee_meditation_sessions', ['local_date'], unique=False)
    op.create_index(op.f('ix_coffee_meditation_sessions_started_at'), 'coffee_meditation_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_coffee_meditation_sessions_user_id'), 'coffee_meditation_sessions', ['user_id'], unique=False)
    op.create_table('coffee_meditation_rejoiced_seeds',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('seed_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['seed_id'], ['seeds.id'], name=op.f('fk_coffee_meditation_rejoiced_seeds_seed_id_seeds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['coffee_meditation_sessions.id'], name=op.f('fk_coffee_meditation_rejoiced_seeds_session_id_coffee_meditation_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'seed_id', name=op.f('pk_coffee_meditation_rejoiced_seeds'))
    )
    op.create_index(op.f('ix_coffee_meditation_rejoiced_seeds_seed_id'), 'coffee_meditation_rejoiced_seeds', ['seed_id'], unique=False)
    op.add_column('seeds', sa.Column('rejoice_count', sa.Integer(), nullable=True))
    op.add_column('seeds', sa.Column('last_rejoiced_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seeds', 'last_rejoiced_at')
    op.drop_column('seeds', 'rejoice_count')
    op.drop_index(op.f('ix_coffee_meditation_rejoiced_seeds_seed_id'), table_name='coffee_meditation_rejoiced_seeds')
    op.drop_table('coffee_meditation_rejoiced_seeds')
    op.drop_index(op.f('ix_coffee_meditation_sessions_user_id'), table_name='coffee_meditation_sessions')
    op.drop_index(op.f('ix_coffee_meditation_sessions_started_at'), table_name='coffee_meditation_sessions')
    op.drop_index(op.f('ix_coffee_meditation_sessions_local_date'), table_name='coffee_meditation_sessions')
    op.drop_index(op.f('ix_coffee_meditation_sessions_karma_plan_id'), table_name='coffee_meditation_sessions')
    op.drop_index(op.f('ix_coffee_meditation_sessions_daily_plan_id'), table_name='coffee_meditation_sessions')
    op.drop_index(op.f('ix_coffee_meditation_sessions_completed_at'), table_name='coffee_meditation_sessions')
    op.drop_table('coffee_meditation_sessions')
    # ### end Alembic commands ###
