"""practices_habits_refactor_drop_habits_add_columns

Revision ID: ad8042a6424c
Revises: 7e220614872f
Create Date: 2026-02-27 17:54:34.799450+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad8042a6424c'
down_revision: Union[str, None] = '7e220614872f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('habit_completions')
    op.drop_table('habits')
    op.add_column('practice_progress', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    op.add_column('practice_progress', sa.Column('is_hidden', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.add_column('practice_progress', sa.Column('karma_plan_id', sa.String(), nullable=True))
    op.create_foreign_key(op.f('fk_practice_progress_karma_plan_id_karma_plans'), 'practice_progress', 'karma_plans', ['karma_plan_id'], ['id'], ondelete='SET NULL')
    op.add_column('practices', sa.Column('difficulty', sa.Integer(), nullable=True))
    op.add_column('practices', sa.Column('max_completions_per_day', sa.Integer(), nullable=True))
    op.add_column('practices', sa.Column('habit_min_streak_days', sa.Integer(), nullable=True))
    op.add_column('practices', sa.Column('habit_min_score', sa.Integer(), nullable=True))
    op.add_column('practices', sa.Column('steps', sa.JSON(), nullable=True))
    op.add_column('practices', sa.Column('contraindications', sa.JSON(), nullable=True))
    op.add_column('practices', sa.Column('benefits', sa.Text(), nullable=True))
    op.add_column('practices', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('seeds', sa.Column('practice_id', sa.String(), nullable=True))
    op.create_foreign_key(op.f('fk_seeds_practice_id_practices'), 'seeds', 'practices', ['practice_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_seeds_practice_id_practices'), 'seeds', type_='foreignkey')
    op.drop_column('seeds', 'practice_id')
    op.drop_column('practices', 'tags')
    op.drop_column('practices', 'benefits')
    op.drop_column('practices', 'contraindications')
    op.drop_column('practices', 'steps')
    op.drop_column('practices', 'habit_min_score')
    op.drop_column('practices', 'habit_min_streak_days')
    op.drop_column('practices', 'max_completions_per_day')
    op.drop_column('practices', 'difficulty')
    op.drop_constraint(op.f('fk_practice_progress_karma_plan_id_karma_plans'), 'practice_progress', type_='foreignkey')
    op.drop_column('practice_progress', 'karma_plan_id')
    op.drop_column('practice_progress', 'is_hidden')
    op.drop_column('practice_progress', 'is_active')
    op.create_table('habit_completions',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('habit_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('duration_actual', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], name=op.f('habit_completions_habit_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('habit_completions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('habit_completions_pkey'))
    )
    op.create_table('habits',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('practice_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('frequency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('preferred_time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('streak', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_completed', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completion_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('user_restrictions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], name=op.f('habits_practice_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('habits_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('habits_pkey'))
    )
    # ### end Alembic commands ###
