"""add_account_link_tokens_and_link_prompt_dismissed

Revision ID: e0f26ced8de8
Revises: 417d3acb4b9b
Create Date: 2026-03-01 02:05:44.330528+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0f26ced8de8'
down_revision: Union[str, None] = '417d3acb4b9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_link_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('token_type', sa.String(), nullable=False),
    sa.Column('target_email', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_account_link_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_link_tokens')),
    sa.UniqueConstraint('token', name=op.f('uq_account_link_tokens_token'))
    )
    op.create_index('idx_account_link_tokens_token', 'account_link_tokens', ['token'], unique=True)
    op.create_index('idx_account_link_tokens_user_type', 'account_link_tokens', ['user_id', 'token_type'], unique=False)
    op.create_index(op.f('ix_account_link_tokens_user_id'), 'account_link_tokens', ['user_id'], unique=False)
    op.add_column('users', sa.Column('link_prompt_dismissed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'link_prompt_dismissed')
    op.drop_index(op.f('ix_account_link_tokens_user_id'), table_name='account_link_tokens')
    op.drop_index('idx_account_link_tokens_user_type', table_name='account_link_tokens')
    op.drop_index('idx_account_link_tokens_token', table_name='account_link_tokens')
    op.drop_table('account_link_tokens')
    # ### end Alembic commands ###
