"""add_daily_suggestions_model

Revision ID: 97bde2a72b35
Revises: 57fe60c447dd
Create Date: 2026-02-04 04:52:18.479908+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97bde2a72b35'
down_revision: Union[str, None] = '57fe60c447dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_suggestions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('why', sa.Text(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('seed_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['seed_id'], ['seeds.id'], name=op.f('fk_daily_suggestions_seed_id_seeds'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_suggestions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_suggestions_completed'), 'daily_suggestions', ['completed'], unique=False)
    op.create_index(op.f('ix_daily_suggestions_date'), 'daily_suggestions', ['date'], unique=False)
    op.create_index(op.f('ix_daily_suggestions_user_id'), 'daily_suggestions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_suggestions_user_id'), table_name='daily_suggestions')
    op.drop_index(op.f('ix_daily_suggestions_date'), table_name='daily_suggestions')
    op.drop_index(op.f('ix_daily_suggestions_completed'), table_name='daily_suggestions')
    op.drop_table('daily_suggestions')
    # ### end Alembic commands ###
