"""add karma project tables

Revision ID: 456789abcdef
Revises: e12843301bc3
Create Date: 2026-02-09 00:00:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '456789abcdef'
down_revision: Union[str, None] = 'e12843301bc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('karma_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_history_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('strategy_snapshot', sa.JSON(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['problem_history_id'], ['problem_history.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_karma_plans_status'), 'karma_plans', ['status'], unique=False)
    op.create_index(op.f('ix_karma_plans_user_id'), 'karma_plans', ['user_id'], unique=False)
    
    op.create_table('daily_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('karma_plan_id', sa.String(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('focus_quality', sa.String(), nullable=True),
    sa.Column('tasks', sa.JSON(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['karma_plan_id'], ['karma_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_plans_karma_plan_id'), 'daily_plans', ['karma_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_plans_karma_plan_id'), table_name='daily_plans')
    op.drop_table('daily_plans')
    op.drop_index(op.f('ix_karma_plans_user_id'), table_name='karma_plans')
    op.drop_index(op.f('ix_karma_plans_status'), table_name='karma_plans')
    op.drop_table('karma_plans')
    # ### end Alembic commands ###
