"""add_partner_and_action_type_to_daily_tasks

Revision ID: dba077286716
Revises: 197b7cb8a67a
Create Date: 2026-02-26 01:07:56.161086+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dba077286716'
down_revision: Union[str, None] = '197b7cb8a67a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_tasks', sa.Column('partner_id', sa.String(), nullable=True))
    op.add_column('daily_tasks', sa.Column('action_type', sa.String(), nullable=True))
    op.create_index(op.f('ix_daily_tasks_action_type'), 'daily_tasks', ['action_type'], unique=False)
    op.create_foreign_key(op.f('fk_daily_tasks_partner_id_partners'), 'daily_tasks', 'partners', ['partner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_daily_tasks_partner_id_partners'), 'daily_tasks', type_='foreignkey')
    op.drop_index(op.f('ix_daily_tasks_action_type'), table_name='daily_tasks')
    op.drop_column('daily_tasks', 'action_type')
    op.drop_column('daily_tasks', 'partner_id')
    # ### end Alembic commands ###
