"""add_diagnostic_json_to_problem_history

Revision ID: c56f551755dc
Revises: 2026_02_19_0002
Create Date: 2026-02-24 01:28:14.925525+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c56f551755dc'
down_revision: Union[str, None] = '2026_02_19_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partners', 'contact_type',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.add_column('problem_history', sa.Column('diagnostic_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem_history', 'diagnostic_json')
    op.alter_column('partners', 'contact_type',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'physical'::character varying"),
               existing_nullable=True)
    # ### end Alembic commands ###
