"""practiсу progress

Revision ID: 7e220614872f
Revises: 4512945064a7
Create Date: 2026-02-27 00:09:08.389630+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e220614872f'
down_revision: Union[str, None] = '4512945064a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_progress',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('practice_id', sa.String(), nullable=False),
    sa.Column('habit_score', sa.Integer(), nullable=True),
    sa.Column('streak_days', sa.Integer(), nullable=True),
    sa.Column('total_completions', sa.Integer(), nullable=True),
    sa.Column('last_completed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_habit', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], name=op.f('fk_practice_progress_practice_id_practices')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_practice_progress_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_progress'))
    )
    op.create_index('idx_user_practice_progress', 'practice_progress', ['user_id', 'practice_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_practice_progress', table_name='practice_progress')
    op.drop_table('practice_progress')
    # ### end Alembic commands ###
