"""add_message_snapshot_to_daily_plans

Revision ID: d52c14c4bda0
Revises: 3a06f1e01ddc
Create Date: 2026-02-24 03:55:08.636789+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd52c14c4bda0'
down_revision: Union[str, None] = '3a06f1e01ddc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_plans', sa.Column('message_snapshot', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_plans', 'message_snapshot')
    # ### end Alembic commands ###
