"""update foreng keys

Revision ID: dd26acad5f42
Revises: a03c6a6c46e7
Create Date: 2026-03-06 01:54:37.624114+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd26acad5f42'
down_revision: Union[str, None] = 'a03c6a6c46e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('partner_groups_user_id_fkey'), 'partner_groups', type_='foreignkey')
    op.create_foreign_key(op.f('fk_partner_groups_user_id_users'), 'partner_groups', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('partners_group_id_fkey'), 'partners', type_='foreignkey')
    op.drop_constraint(op.f('partners_user_id_fkey'), 'partners', type_='foreignkey')
    op.create_foreign_key(op.f('fk_partners_user_id_users'), 'partners', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_partners_group_id_partner_groups'), 'partners', 'partner_groups', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_partners_group_id_partner_groups'), 'partners', type_='foreignkey')
    op.drop_constraint(op.f('fk_partners_user_id_users'), 'partners', type_='foreignkey')
    op.create_foreign_key(op.f('partners_user_id_fkey'), 'partners', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('partners_group_id_fkey'), 'partners', 'partner_groups', ['group_id'], ['id'])
    op.drop_constraint(op.f('fk_partner_groups_user_id_users'), 'partner_groups', type_='foreignkey')
    op.create_foreign_key(op.f('partner_groups_user_id_fkey'), 'partner_groups', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
