"""extract_daily_tasks_and_link_seeds

Revision ID: 197b7cb8a67a
Revises: 88d01c711cdb
Create Date: 2026-02-25 19:52:36.065689+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '197b7cb8a67a'
down_revision: Union[str, None] = '88d01c711cdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('daily_plan_id', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('why', sa.Text(), nullable=True),
    sa.Column('group', sa.String(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['daily_plan_id'], ['daily_plans.id'], name=op.f('fk_daily_tasks_daily_plan_id_daily_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_tasks'))
    )
    op.create_index(op.f('ix_daily_tasks_completed'), 'daily_tasks', ['completed'], unique=False)
    op.create_index(op.f('ix_daily_tasks_daily_plan_id'), 'daily_tasks', ['daily_plan_id'], unique=False)
    op.drop_column('daily_plans', 'tasks')
    op.add_column('seeds', sa.Column('karma_plan_id', sa.String(), nullable=True))
    op.add_column('seeds', sa.Column('daily_plan_id', sa.String(), nullable=True))
    op.add_column('seeds', sa.Column('daily_task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_seeds_daily_plan_id_daily_plans'), 'seeds', 'daily_plans', ['daily_plan_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_seeds_daily_task_id_daily_tasks'), 'seeds', 'daily_tasks', ['daily_task_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_seeds_karma_plan_id_karma_plans'), 'seeds', 'karma_plans', ['karma_plan_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_seeds_karma_plan_id_karma_plans'), 'seeds', type_='foreignkey')
    op.drop_constraint(op.f('fk_seeds_daily_task_id_daily_tasks'), 'seeds', type_='foreignkey')
    op.drop_constraint(op.f('fk_seeds_daily_plan_id_daily_plans'), 'seeds', type_='foreignkey')
    op.drop_column('seeds', 'daily_task_id')
    op.drop_column('seeds', 'daily_plan_id')
    op.drop_column('seeds', 'karma_plan_id')
    op.add_column('daily_plans', sa.Column('tasks', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_daily_tasks_daily_plan_id'), table_name='daily_tasks')
    op.drop_index(op.f('ix_daily_tasks_completed'), table_name='daily_tasks')
    op.drop_table('daily_tasks')
    # ### end Alembic commands ###
